---
title: "Appendix"
author: "Ethan Shen, Austin Jia, Malavi Ravindran, Steven Herrera"
date: "10/26/2019"
output: pdf_document
---

```{r warning = FALSE, message = FALSE, echo = FALSE}
set.seed(123)
# Installing packages
pkgTest <- function(x) {
  if (!require(x,character.only = TRUE)) {
    install.packages(x,dep=TRUE)
  }
}
pkgs <- c("tidyverse", "cowplot", "LaplacesDemon", "gam", "gamclass", "mgcv")
for (pkg in pkgs) {
  pkgTest(pkg)
}

library(tidyverse)
library(cowplot)
library(grid)
library(gridExtra)
library(LaplacesDemon)
library(gam)
library(gamclass)
library(mgcv)

train <- read.csv("data-train.csv") 
test <- read.csv("data-test.csv")

train <- train %>%
  mutate(log_first_moment = log(R_moment_1),
         log_second_moment = log(R_moment_2),
         log_third_moment = log(R_moment_3),
         log_fourth_moment = log(R_moment_4))
train$Fr <- invlogit(train$Fr)
test$Fr <- invlogit(test$Fr)
```

# A - Model Output for Each Moment 

```{r warning = FALSE, message = FALSE, echo = FALSE}
lm.fit.log.1 <- lm(log_first_moment ~ St + log(Re) + log(Fr), data = train)
print("Model 1 Output")
summary(lm.fit.log.1)
lm.fit.2 <- lm(log_second_moment ~ St + Re + Fr + Re*Fr, data=train)
print("Model 2 Output")
summary(lm.fit.2)
gam.fit.3 <- gam(log_third_moment~ s(log(St)) + Re + Fr + Re:Fr, data=train)
print("Model 3 Output")
summary(gam.fit.3)
gam.fit.4 <- gam(log_fourth_moment ~ ns(St) + Re + Fr + Re:Fr, data = train)
print("Model 4 Output")
summary(gam.fit.4)
```

# B.1 - Residuals of Moment 1 Models

```{r warning = FALSE, message = FALSE, echo = FALSE}
lm.fit.1 <- lm(log_first_moment ~ St + Re + Fr, data = train)

a <- train %>%
  mutate(residuals = resid(lm.fit.1))

a1 <- ggplot(data=a,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

a2 <- ggplot(data=a,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

a3 <- ggplot(data=a,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

a4 <- ggplot(data=a,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_1 <- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 1") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_1, plot_grid(a1, a2, a3, a4), ncol = 1, rel_heights = c(0.1,1))
```


```{r warning = FALSE, message = FALSE, echo = FALSE}
alog <- train %>%
  mutate(residuals = resid(lm.fit.log.1))

a1log <- ggplot(data=alog,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

a2log <- ggplot(data=alog,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

a3log <- ggplot(data=alog,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

a4log <- ggplot(data=alog,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_1.log <- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 1 with Logged Predictors") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_1.log, plot_grid(a1log, a2log, a3log, a4log), ncol = 1, rel_heights = c(0.1,1))
```

# B.2 - Residuals of Moment 2 Models

```{r warning = FALSE, message = FALSE, echo = FALSE}
lm.fit.2 <- lm(log_second_moment ~ St + Re + Fr + Re*Fr, data=train)

b <- train %>%
  mutate(residuals = resid(lm.fit.2))

b1 <- ggplot(data=b,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

b2 <- ggplot(data=b,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

b3 <- ggplot(data=b,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

b4 <- ggplot(data=b,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_2 <- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 2") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_2, plot_grid(b1, b2, b3, b4), ncol = 1, rel_heights = c(0.1,1))
```

```{r warning = FALSE, message = FALSE, echo = FALSE}
lm.fit.log.2 <- lm(log_second_moment ~ St + log(Re) + log(Fr) + log(Re) * log(Fr), data=train)

b.log <- train %>%
  mutate(residuals = resid(lm.fit.log.2))

b1.log <- ggplot(data=b.log,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

b2.log <- ggplot(data=b.log,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

b3.log <- ggplot(data=b.log,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

b4.log <- ggplot(data=b.log,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_2.log<- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 2 with Logged Predictors") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_2.log, plot_grid(b1.log, b2.log, b3.log, b4.log), ncol = 1, rel_heights = c(0.1,1))
```

# B.3 - Residuals of Moment 3 Models

```{r warning = FALSE, message = FALSE, echo = FALSE}
c <- train %>%
  mutate(residuals = resid(gam.fit.3))

c1 <- ggplot(data=c,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

c2 <- ggplot(data=c,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

c3 <- ggplot(data=c,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

c4 <- ggplot(data=c,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_3 <- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 3") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_3, plot_grid(c1, c2, c3, c4), ncol = 1, rel_heights = c(0.1,1))
```

```{r warning = FALSE, message = FALSE, echo = FALSE}
gam.fit.log.3 <- gam(log_third_moment~ s(log(St)) + log(Re) + log(Fr) + log(Re):log(Fr), data=train)

c.log <- train %>%
  mutate(residuals = resid(gam.fit.log.3))

c1 <- ggplot(data=c.log,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

c2 <- ggplot(data=c.log,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

c3 <- ggplot(data=c.log,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

c4 <- ggplot(data=c.log,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_3.log <- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 3 with Logged Predictors") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_3.log, plot_grid(c1, c2, c3, c4), ncol = 1, rel_heights = c(0.1,1))
```

# B.4 - Residuals of Moment 4 Models

```{r warning = FALSE, message = FALSE, echo = FALSE}
d <- train %>%
  mutate(residuals = resid(gam.fit.4))

d1 <- ggplot(data=d,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

d2 <- ggplot(data=d,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

d3 <- ggplot(data=d,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

d4 <- ggplot(data=d,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_4 <- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 4") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_4, plot_grid(d1, d2, d3, d4), ncol = 1, rel_heights = c(0.1,1))
```

```{r warning = FALSE, message = FALSE, echo = FALSE}
gam.fit.log.4 <- gam(log_fourth_moment ~ ns(St) + log(Re) + log(Fr) + log(Re):log(Fr), data = train)

d.log <- train %>%
  mutate(residuals = resid(gam.fit.log.4))

d1 <- ggplot(data=d.log,mapping=aes(x=St, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. St")

d2 <- ggplot(data=d.log,mapping=aes(x=Re, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Re")

d3 <- ggplot(data=d.log,mapping=aes(x=Fr, y=residuals)) + 
  geom_point() + 
  geom_hline(yintercept=0,color="red") + 
  labs(title = "Residuals vs. Fr")

d4 <- ggplot(data=d.log,mapping=aes(sample=residuals)) + 
  stat_qq() + 
  stat_qq_line() +
  labs(title="Normal QQ Plot of Residuals")

title_4.log <- ggdraw() + 
  draw_label("Residuals of Model with Logged Moment 4 with Logged Predictors")+
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title_4.log, plot_grid(d1, d2, d3, d4), ncol = 1, rel_heights = c(0.1,1))
```


```{r warning = FALSE, message = FALSE}
i1 <- ggplot(data=train, aes(x=St,y=log_first_moment, color=as.factor(round(Fr, 3)))) + 
  geom_smooth() + 
  labs(y = "log(Moment 1)",
       color = "Fr")
i2 <- ggplot(data=train, aes(x=St,y=log_second_moment, color=as.factor(round(Fr, 3)))) + 
  geom_smooth() + 
  labs(y = "log(Moment 2)",
       color = "Fr")
i3 <- ggplot(data=train, aes(x=St,y=log_third_moment, color=as.factor(round(Fr, 3)))) + 
  geom_smooth() + 
  labs(y = "log(Moment 3)",
       color = "Fr")
i4 <- ggplot(data=train, aes(x=St,y=log_fourth_moment, color=as.factor(round(Fr, 3)))) + 
  geom_smooth() + 
  labs(y = "log(Moment 4)",
       color = "Fr")

title_i <- ggdraw() + 
  draw_label("Interaction between St and Fr") +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_i <- plot_grid(
  i1 + theme(legend.position = "none"),
  i2 + theme(legend.position = "none"),
  i3 + theme(legend.position = "none"),
  i4 + theme(legend.position = "none"),
  nrow = 2
)

legend <- get_legend(i1)

with_title <- plot_grid(title_i, plot_i, ncol =1, rel_heights = c(0.1,1))

plot_grid(with_title, legend, rel_widths = c(3, 0.4))
```