---
title: "STA 325 - Data Expedition"
author: "Ethan Shen, Austin Jia, Malavi Ravindran, Steven Herrera"
date: "10/26/2019"
output: rmdformats::readthedown
---

```{r, echo = FALSE, include = FALSE}
# Installing packages
pkgTest <- function(x) {
  if (!require(x,character.only = TRUE)) {
    install.packages(x,dep=TRUE)
  }
}
pkgs <- c("ggplot2", "cowplot", "LaplacesDemon")
for (pkg in pkgs) {
  pkgTest(pkg)
}
```

```{r, include = FALSE, echo = FALSE}
library(ggplot2)
library(cowplot)
library(LaplacesDemon)
```

```{r}
train <- read.csv("data-train.csv")
test <- read.csv("data-test.csv")
```

# Exploratory Data Analysis

```{r}
p1 <- qplot(train$St, bins = 20, 
      main = "Distribution of St", 
      xlab = "St", 
      ylab = "Frequency")

p2 <- qplot(train$Re, bins = 20,
      main = "Distribution of Re", 
      xlab = "Re", 
      ylab = "Frequency")

p3 <- qplot(train$Fr, bins = 20,
      main = "Distribution of Fr", 
      xlab = "Fr", 
      ylab = "Frequency")

plot_grid(p1,p2,p3)
```


```{r}
train$Fr <- invlogit(train$Fr)
qplot(train$Fr, bins = 20,
      main = "Distribution of Fr", 
      xlab = "Fr", 
      ylab = "Frequency")

```

### General Framework

### Linear Model (log transformations)

### Polynomial 

### GAMs

### Splines

### Random Forest

### Cross Validation

```{r, include=FALSE}
cross_validate <- function(model_type, formula, data, k, log_response) {
  #Randomly shuffle the data
  shuffled_data<-data[sample(nrow(data)),]
  #Create 10 equally size folds
  folds <- cut(seq(1,nrow(shuffled_data)),breaks=k,labels=FALSE)
  #Perform 10 fold cross validation
  avg_mse <- 0
  for(i in 1:k){
    #Segement your data by fold using the which() function 
    testIndexes <- which(folds==i,arr.ind=TRUE)
    testData <- shuffled_data[testIndexes, ]
    trainData <- shuffled_data[-testIndexes, ]
    
    model <- model_type(as.formula(formula), data=trainData)
    # validate model
    if (log_response) {
      test_mse <-  mean((exp(predict(model, testData)) - testData$BWTG_C)^2)
    }
    else {
      test_mse <- mean((predict(model, testData) - testData$BWTG_C)^2)
    }
    avg_mse <- avg_mse + test_mse
    }
  print('Average test MSE')
  print(avg_mse / k)
  return (avg_mse / k)
}
```

